version: "3.8"
services:
  lpd-officer-monitor:
    container_name: lpdbot
    build: ./
    stdin_open: true
    tty: true
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      DISCORD_TOKEN_FILE: /run/secrets/discord_token
      DISCORD_SECRET_FILE: /run/secrets/discord_secret
      LPD_OFFICER_MONITOR_ENVIRONMENT: "${LPD_OFFICER_MONITOR_ENVIRONMENT}"
    volumes:
      - ".:/app"
    secrets:
      - mysql_user_password
      - discord_token
      - discord_secret
    depends_on:
      - db
    #restart: on-failure:1
    restart: unless-stopped #the only way to get autostart

  db:
    image: mariadb:10.6 #LTS
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_DATABASE: LPD_Officer_Monitor_v3
      MYSQL_USER: lpdbot
      TZ: "Etc/UTC"
    ports:
      - "3306:3306"
    volumes:
      - db-data:/var/lib/mysql
    secrets:
      - mysql_root_password
      - mysql_user_password

volumes:
  db-data: null

secrets:
  mysql_root_password:
    file: mysql_root_password
  mysql_user_password:
    file: mysql_user_password
  discord_token:
    file: discord_token
  discord_secret:
    file: discord_secret
