services:
  lpdbot:
    container_name: lpdbot
    build:
      context: .
      dockerfile: Dockerfile
      args:
          BUILD_TYPE: ${LPD_OFFICER_MONITOR_ENVIRONMENT}
    stdin_open: true
    tty: true
    environment:
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      DISCORD_TOKEN_FILE: /run/secrets/discord_token
      LPD_OFFICER_MONITOR_ENVIRONMENT: "${LPD_OFFICER_MONITOR_ENVIRONMENT}"
    volumes:
      - ".:/app:ro"
      - /app/.venv
      - "./logs:/logs:rw"
      - "./settings/local.ini:/app/settings/local.ini:rw"
    secrets:
      - mysql_user_password
      - discord_token
    depends_on:
      - db
    #restart: on-failure:1
    restart: unless-stopped #the only way to get autostart

  db:
    #image: mariadb:10.6 #LTS
    image: mariadb:12.2
    container_name: db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD_FILE: /run/secrets/mysql_root_password
      MYSQL_PASSWORD_FILE: /run/secrets/mysql_user_password
      MYSQL_DATABASE: LPD_Officer_Monitor_v3
      MYSQL_USER: lpdbot
      TZ: "Etc/UTC"
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - db-data:/var/lib/mysql
      - ./extra/mariadb/custom.cnf:/etc/mysql/conf.d/custom.cnf:ro
    secrets:
      - mysql_root_password
      - mysql_user_password
      - mariadb_keys
      - mariadb_keyfile

volumes:
  db-data: null

secrets:
  mysql_root_password:
    file: mysql_root_password
  mysql_user_password:
    file: mysql_user_password
  discord_token:
    file: discord_token
  mariadb_keys:
    file: ./extra/mariadb/encryption/keys.enc
  mariadb_keyfile:
    file: ./extra/mariadb/encryption/keyfile.key
