[pytest]
env =
    LPD_OFFICER_MONITOR_UNIT_TESTING=TRUE
log_cli = True
markers =
    reset_db: mark test to reset database to known state
filterwarnings =
    #error
    ignore:PyNaCl
    ignore:upload_to_world_task
