"""Patrol measurement models

Revision ID: 1acd4e378f65
Revises: 
Create Date: 2022-05-17 21:56:35.267440

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1acd4e378f65'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patrols',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('officer', sa.BigInteger(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event', sa.Integer(), nullable=True),
    sa.Column('main_channel', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['event'], ['events.id'], name='fk_patrols_events_id_event'),
    sa.ForeignKeyConstraint(['main_channel'], ['savedvoicechannels.id'], name='fk_patrols_savedvoicechannels_id_main_channel'),
    sa.ForeignKeyConstraint(['officer'], ['officers.id'], name='fk_patrols_officers_id_officer'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('patrolvoices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patrol', sa.Integer(), nullable=True),
    sa.Column('channel', sa.BigInteger(), nullable=True),
    sa.Column('start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['channel'], ['savedvoicechannels.id'], name='fk_patrolvoices_savedvoicechannels_id_channel'),
    sa.ForeignKeyConstraint(['patrol'], ['patrols.id'], name='fk_patrolvoices_patrols_id_patrol'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('badgecategory')
    op.drop_table('detainedusers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detainedusers',
    sa.Column('id', mysql.BIGINT(), autoincrement=True, nullable=False),
    sa.Column('role_ids', mysql.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('badgecategory',
    sa.Column('id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('patrolvoices')
    op.drop_table('patrols')
    # ### end Alembic commands ###
