"""Added deleted_at to officer

Revision ID: 37120c7c41f4
Revises: 5c2501b30fbb
Create Date: 2022-05-18 23:02:39.528509

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37120c7c41f4'
down_revision = '5c2501b30fbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('officers', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('officers', 'deleted_at')
    # ### end Alembic commands ###
